version: '2.2'
services:
    app:
        container_name: dockerized-react-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
            # - ./src:/usr/src/app
            # - ./public:/usr/src/app
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development